POST https://travelco-api-zeta.vercel.app/api/auth/login
Content-Type: application/json
x-api-key: travelco2023

{
    "username": "geusan31",
    "password": "geusan31"
}

###
GET https://travelco-api-zeta.vercel.app/api/users/get-user


###
POST https://travelco-api-zeta.vercel.app/api/users/add-user
Content-Type: application/json
x-api-key: travelco2023

{
    "nama": "Geusan Edurais",
    "username": "geusan31",
    "password": "geusan31",
    "email": "geusan31@gmail.com",
    "password": "geusan31"
}

###
PATCH https://travelco-api-zeta.vercel.app/api/users/update-user?id=1
Content-Type: application/json
x-api-key: travelco2023

{
    "role": "ADMIN"
}

###
##DELETE USER
DELETE  https://travelco-api-zeta.vercel.app/api/users/delete-user?id=37
x-api-key: travelco2023

###
GET https://travelco-api-zeta.vercel.app/api/cart/get-cart-user?id=1
x-api-key: travelco2023